// <auto-generated />
using System;
using FlowrSpot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowrSpot.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231212211819_SeedDbTablesFlowersUsers")]
    partial class SeedDbTablesFlowersUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowrSpot.Domain.Entities.Flower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Flowers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60164c52-e90c-4315-9f4e-95ae1c9f1f03"),
                            Description = "Red rose",
                            ImageUrl = "some/imge/rose_url.jpg",
                            Name = "Rose"
                        },
                        new
                        {
                            Id = new Guid("749778b3-6756-45cc-a5fb-64e8162f5ce8"),
                            Description = "Yellow tulip",
                            ImageUrl = "some/imge/tulip_url.jpg",
                            Name = "Tulip"
                        },
                        new
                        {
                            Id = new Guid("a9537e9e-b3df-4f91-9eb3-f6bf27026ff0"),
                            Description = "Yellow daffodil",
                            ImageUrl = "some/imge/daffodil_url.jpg",
                            Name = "Daffodil"
                        });
                });

            modelBuilder.Entity("FlowrSpot.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa39a862-764b-4797-938f-e562150393f9"),
                            Email = "bob44@yahoo.com",
                            Password = "bob123",
                            Username = "Bob44"
                        },
                        new
                        {
                            Id = new Guid("7a7782d7-231f-4239-a489-aa0fc53f7012"),
                            Email = "test123@yahoo.com",
                            Password = "test123",
                            Username = "test123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
